/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 6913811847b5bf7419a0f1013989cba4)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	PARTY_EVENTS: DurableObjectNamespace<import("./src/cloudflare/worker").PartyEventDurableObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cloudflare/worker");
		durableNamespaces: "PartyEventDurableObject";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
