import type {
  Cue,
  EventState,
  Guest,
  Interaction,
  Mission,
  PartyTable,
  Stage,
} from "./types";

const SEEDED_AT = "2026-09-17T03:32:49.000Z";

function indexById<T extends { id: string }>(items: T[]): Record<string, T> {
  return Object.fromEntries(items.map((item) => [item.id, item]));
}

export function createDemoEventState(): EventState {
  const tables: PartyTable[] = [
    { id: "table-a", name: "A TABLE", color: "#ff6b57" },
    { id: "table-b", name: "B TABLE", color: "#ffd166" },
    { id: "table-c", name: "C TABLE", color: "#5eead4" },
    { id: "table-d", name: "D TABLE", color: "#a78bfa" },
  ];

  const stages: Stage[] = [
    {
      id: "stage-check-in",
      title: "CHECK IN",
      shortLabel: "입장",
      description: "QR로 입장하고 오늘의 파티 온도를 확인합니다.",
      cueOrder: ["cue-welcome", "cue-room-rule", "cue-checkin-mood"],
    },
    {
      id: "stage-warm-up",
      title: "WARM UP",
      shortLabel: "워밍업",
      description: "처음 만난 하객과 인사하고 테이블의 목소리를 엽니다.",
      cueOrder: [
        "cue-warmup-intro",
        "cue-first-toast",
        "cue-name-chain",
        "cue-warmup-energy",
        "cue-warmup-cheer",
      ],
    },
    {
      id: "stage-telepathy",
      title: "TELEPATHY",
      shortLabel: "텔레파시",
      description: "커플과 하객의 예상이 얼마나 통하는지 확인합니다.",
      cueOrder: [
        "cue-telepathy-intro",
        "cue-telepathy-prediction",
        "cue-telepathy-first-contact",
        "cue-telepathy-weekend",
        "cue-telepathy-finale",
      ],
    },
    {
      id: "stage-beat-groom",
      title: "BEAT THE GROOM",
      shortLabel: "신랑을 이겨라",
      description: "도전자를 응원하고 승부의 결과를 함께 예측합니다.",
      cueOrder: ["cue-challenger", "cue-beat-groom-prediction", "cue-groom-cheer"],
    },
    {
      id: "stage-table-battle",
      title: "TABLE BATTLE",
      shortLabel: "테이블 배틀",
      description: "테이블이 함께 답하고 움직이며 점수를 모읍니다.",
      cueOrder: [
        "cue-table-intro",
        "cue-table-quiz",
        "cue-table-anniversary",
        "cue-table-boutonniere",
        "cue-table-pose",
        "cue-table-leaderboard",
      ],
    },
    {
      id: "stage-relationship",
      title: "RELATIONSHIP",
      shortLabel: "관계도",
      description: "오늘 모인 사람들의 인연과 새로운 공통점을 발견합니다.",
      cueOrder: ["cue-relationship", "cue-relationship-poll", "cue-common-point"],
    },
    {
      id: "stage-secret-mission",
      title: "SECRET MISSION",
      shortLabel: "시크릿 미션",
      description: "휴대폰을 내려놓고 아직 만나지 않은 사람과 연결됩니다.",
      cueOrder: [
        "cue-secret-intro",
        "cue-opposite-side",
        "cue-specific-compliment",
        "cue-table-photo",
        "cue-introduce-guests",
      ],
    },
    {
      id: "stage-finale",
      title: "FINALE",
      shortLabel: "피날레",
      description: "오늘의 선택과 점수를 한 화면에서 마무리합니다.",
      cueOrder: ["cue-finale-intro", "cue-finale-mvp", "cue-finale", "cue-finale-thanks"],
    },
    {
      id: "stage-after-party",
      title: "AFTER PARTY",
      shortLabel: "애프터 파티",
      description: "공식 진행을 닫고 음악·사진·대화를 이어갑니다.",
      cueOrder: ["cue-after-party", "cue-after-song", "cue-after-photo"],
    },
  ];

  const cues: Cue[] = [
    {
      id: "cue-welcome",
      stageId: "stage-check-in",
      title: "Welcome",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "근성순대 AFTER PARTY",
        headline: "오늘 밤, 같이 놀 준비됐나요?",
        body: "QR을 찍고 이름·인연·테이블을 고르면 바로 입장합니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-room-rule",
      stageId: "stage-check-in",
      title: "오늘의 한 가지 규칙",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "ONE RULE TONIGHT",
        headline: "휴대폰보다 사람을 먼저 봐주세요.",
        body: "화면은 필요한 순간에만 켜고, 미션이 열리면 옆 사람과 함께 움직입니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-checkin-mood",
      stageId: "stage-check-in",
      title: "오늘의 파티 온도",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-checkin-mood" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-warmup-intro",
      stageId: "stage-warm-up",
      title: "Warm Up Start",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "WARM UP",
        headline: "같은 테이블부터 서로의 이름을 열어볼까요?",
        body: "첫 미션이 공개되면 오늘 처음 만난 사람과 짧게 인사합니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-first-toast",
      stageId: "stage-warm-up",
      title: "첫 건배",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-first-toast" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-name-chain",
      stageId: "stage-warm-up",
      title: "이름 릴레이",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-name-chain" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-warmup-energy",
      stageId: "stage-warm-up",
      title: "지금 텐션 체크",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-warmup-energy" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-warmup-cheer",
      stageId: "stage-warm-up",
      title: "테이블 함성",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "TABLE SOUND CHECK",
        headline: "우리 테이블 목소리부터 맞춰볼까요?",
        body: "MC가 테이블을 부르면 가장 짧고 크게 한 번만 외쳐주세요.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-telepathy-intro",
      stageId: "stage-telepathy",
      title: "Telepathy Start",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "TELEPATHY",
        headline: "우리는 두 사람을 얼마나 잘 알고 있을까요?",
        body: "하객이 먼저 예상하고, MC가 두 사람의 실제 답을 확인합니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-telepathy-prediction",
      stageId: "stage-telepathy",
      title: "첫 텔레파시",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-telepathy-match" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-telepathy-first-contact",
      stageId: "stage-telepathy",
      title: "먼저 연락하는 사람",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-first-contact" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-telepathy-weekend",
      stageId: "stage-telepathy",
      title: "완벽한 주말",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-weekend-style" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-telepathy-finale",
      stageId: "stage-telepathy",
      title: "커플 답 공개",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "TELEPATHY RESULT",
        headline: "우리가 예상한 두 사람과 실제 두 사람은 같았을까요?",
        body: "정답보다 중요한 건 왜 그렇게 골랐는지 듣는 순간입니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-challenger",
      stageId: "stage-beat-groom",
      title: "Challenger Wanted",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "CHALLENGER WANTED",
        headline: "신랑에게 도전할 한 사람을 찾습니다.",
        body: "MC가 종목과 도전자를 현장에서 소개합니다. 응원할 준비만 해주세요.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-beat-groom-prediction",
      stageId: "stage-beat-groom",
      title: "승자 예측",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-beat-groom" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-groom-cheer",
      stageId: "stage-beat-groom",
      title: "승부 응원",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-groom-cheer" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-intro",
      stageId: "stage-table-battle",
      title: "Table Battle Start",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "TABLE BATTLE",
        headline: "이번에는 혼자가 아니라 테이블이 함께 답합니다.",
        body: "답을 고르기 전에 10초 동안 테이블 사람들과 의견을 맞춰보세요.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-quiz",
      stageId: "stage-table-battle",
      title: "웨딩 단어 퀴즈",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-table-quiz" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-anniversary",
      stageId: "stage-table-battle",
      title: "기념일 퀴즈",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-anniversary" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-boutonniere",
      stageId: "stage-table-battle",
      title: "부토니에 퀴즈",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-boutonniere" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-pose",
      stageId: "stage-table-battle",
      title: "테이블 단체 포즈",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-table-pose" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-leaderboard",
      stageId: "stage-table-battle",
      title: "Table Leaderboard",
      audience: ["screen"],
      status: "queued",
      payload: { kind: "leaderboard", headline: "TABLE BATTLE" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-relationship",
      stageId: "stage-relationship",
      title: "Who Is This?",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "custom",
        eyebrow: "WHO IS THIS?",
        headline: "이 사람은 두 사람과 어떤 인연일까요?",
        body: "MC가 등록된 인연과 한 줄 소개를 읽고 주인공을 찾습니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-relationship-poll",
      stageId: "stage-relationship",
      title: "오늘 가장 많은 인연",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-relationship" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-common-point",
      stageId: "stage-relationship",
      title: "공통점 하나 찾기",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-common-point" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-secret-intro",
      stageId: "stage-secret-mission",
      title: "Secret Mission Start",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "SECRET MISSION",
        headline: "다음 미션은 화면보다 사람을 봐야 성공합니다.",
        body: "완료 버튼을 누르기 전에 상대의 이름과 인연을 꼭 확인하세요.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-opposite-side",
      stageId: "stage-secret-mission",
      title: "반대편 하객과 건배",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-opposite-side" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-specific-compliment",
      stageId: "stage-secret-mission",
      title: "구체적인 칭찬",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-specific-compliment" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-table-photo",
      stageId: "stage-secret-mission",
      title: "테이블 밖 단체 사진",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-table-photo" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-introduce-guests",
      stageId: "stage-secret-mission",
      title: "하객 소개 연결",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-introduce-guests" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-finale-intro",
      stageId: "stage-finale",
      title: "Finale Start",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "FINALE",
        headline: "오늘의 선택과 점수를 한 화면에 모읍니다.",
        body: "마지막 투표 뒤 테이블 순위와 오늘의 우승을 공개합니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-finale-mvp",
      stageId: "stage-finale",
      title: "오늘의 MVP 테이블",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-finale-mvp" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-finale",
      stageId: "stage-finale",
      title: "Tonight's Winners",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "leaderboard", headline: "TONIGHT'S WINNERS" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-finale-thanks",
      stageId: "stage-finale",
      title: "마지막 인사",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "THANK YOU FOR TONIGHT",
        headline: "오늘의 파티를 같이 만들어주셔서 고맙습니다.",
        body: "이제 점수는 내려놓고, 방금 친해진 사람과 한 잔 더 이어가세요.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-after-party",
      stageId: "stage-after-party",
      title: "After Party",
      audience: ["guest", "screen"],
      status: "queued",
      payload: {
        kind: "announcement",
        eyebrow: "FORMAL PROGRAM: OFF",
        headline: "이제 진짜 파티가 시작됩니다.",
        body: "마시고, 이야기하고, 마음껏 즐겨주세요. 휴대폰은 다시 주머니에 넣어도 됩니다.",
      },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-after-song",
      stageId: "stage-after-party",
      title: "다음 음악 분위기",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "interaction", interactionId: "interaction-after-song" },
      createdAt: SEEDED_AT,
    },
    {
      id: "cue-after-photo",
      stageId: "stage-after-party",
      title: "마지막 사진",
      audience: ["guest", "screen"],
      status: "queued",
      payload: { kind: "mission", missionId: "mission-after-photo" },
      createdAt: SEEDED_AT,
    },
  ];

  const missions: Mission[] = [
    {
      id: "mission-first-toast",
      cueId: "cue-first-toast",
      title: "MISSION #01 · 첫 건배",
      description: "같은 테이블에서 오늘 처음 만난 사람의 이름을 묻고 함께 건배하세요.",
      unlockPhase: "open",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 5,
    },
    {
      id: "mission-name-chain",
      cueId: "cue-name-chain",
      title: "MISSION #02 · 이름 릴레이",
      description: "테이블 전원의 이름을 한 번씩 부른 뒤 마지막 사람이 모두의 이름을 이어 말하세요.",
      unlockPhase: "open",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 5,
    },
    {
      id: "mission-groom-cheer",
      cueId: "cue-groom-cheer",
      title: "MISSION #03 · 승부 응원",
      description: "테이블만의 짧은 응원 구호를 정하고 승부가 시작되면 한 번에 외치세요.",
      unlockPhase: "team",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 5,
    },
    {
      id: "mission-table-pose",
      cueId: "cue-table-pose",
      title: "MISSION #04 · 단체 포즈",
      description: "테이블 전원이 5초 안에 같은 포즈를 만들고 MC에게 보여주세요.",
      unlockPhase: "team",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-common-point",
      cueId: "cue-common-point",
      title: "MISSION #05 · 뜻밖의 공통점",
      description: "다른 테이블 하객 한 명과 대화해 음식·취미·여행 중 공통점 하나를 찾으세요.",
      unlockPhase: "social",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-opposite-side",
      cueId: "cue-opposite-side",
      title: "SECRET #01 · 반대편 건배",
      description: "신랑 측이면 신부 측, 신부 측이면 신랑 측 하객을 찾아 이름을 묻고 건배하세요.",
      unlockPhase: "secret",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-specific-compliment",
      cueId: "cue-specific-compliment",
      title: "SECRET #02 · 구체적인 칭찬",
      description: "오늘 처음 만난 사람에게 옷·말투·분위기 중 하나를 구체적으로 칭찬하세요.",
      unlockPhase: "secret",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-table-photo",
      cueId: "cue-table-photo",
      title: "SECRET #03 · 테이블 밖 사진",
      description: "다른 테이블 하객 두 명 이상과 함께 근성순대 포즈로 사진을 남기세요.",
      unlockPhase: "secret",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-introduce-guests",
      cueId: "cue-introduce-guests",
      title: "SECRET #04 · 인연 연결",
      description: "서로 모르는 하객 두 명을 찾아 이름과 신랑·신부와의 인연을 대신 소개하세요.",
      unlockPhase: "secret",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 10,
    },
    {
      id: "mission-after-photo",
      cueId: "cue-after-photo",
      title: "AFTER MISSION · 마지막 한 장",
      description: "오늘 새로 알게 된 사람과 사진을 찍고 서로의 이름을 다시 확인하세요.",
      unlockPhase: "social",
      status: "locked",
      verification: "self",
      audience: { kind: "all" },
      points: 5,
    },
  ];

  const interactions: Interaction[] = [
    {
      id: "interaction-checkin-mood",
      mode: "poll",
      prompt: "지금 이 파티, 어디까지 갈 수 있을까요?",
      options: [
        { id: "warm", label: "천천히 몸풀기" },
        { id: "ready", label: "이미 준비 완료" },
        { id: "all-night", label: "오늘 끝까지" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-warmup-energy",
      mode: "poll",
      prompt: "우리 테이블의 현재 텐션은?",
      options: [
        { id: "quiet", label: "아직 탐색 중" },
        { id: "warming", label: "슬슬 올라오는 중" },
        { id: "ready", label: "지금 바로 시작" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-telepathy-match",
      mode: "prediction",
      prompt: "첫 질문부터 두 사람의 답이 통할까요?",
      options: [
        { id: "match", label: "통한다" },
        { id: "mismatch", label: "엇갈린다" },
      ],
      correctOptionId: "match",
      phase: "draft",
      scoring: { correct: 10, target: "guest" },
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-first-contact",
      mode: "prediction",
      prompt: "평소 먼저 연락하는 사람은 누구일까요?",
      options: [
        { id: "groom", label: "신랑" },
        { id: "bride", label: "신부" },
        { id: "same", label: "거의 반반" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-weekend-style",
      mode: "prediction",
      prompt: "두 사람이 고를 완벽한 주말은?",
      options: [
        { id: "home", label: "집에서 푹 쉬기" },
        { id: "food", label: "맛집 찾아가기" },
        { id: "travel", label: "일단 떠나기" },
        { id: "friends", label: "사람들과 만나기" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-beat-groom",
      mode: "prediction",
      prompt: "이번 승부의 승자는 누구일까요?",
      options: [
        { id: "groom", label: "신랑" },
        { id: "challenger", label: "도전자" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-table-quiz",
      mode: "quiz",
      prompt: "신부가 손에 드는 꽃다발을 영어로 하면?",
      options: [
        { id: "bouquet", label: "Bouquet" },
        { id: "boutonniere", label: "Boutonniere" },
      ],
      correctOptionId: "bouquet",
      phase: "draft",
      scoring: { correct: 10, target: "table" },
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-anniversary",
      mode: "quiz",
      prompt: "결혼 50주년을 부르는 이름은?",
      options: [
        { id: "gold", label: "금혼식" },
        { id: "silver", label: "은혼식" },
      ],
      correctOptionId: "gold",
      phase: "draft",
      scoring: { correct: 10, target: "table" },
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-boutonniere",
      mode: "quiz",
      prompt: "신랑의 가슴에 다는 작은 꽃 장식은?",
      options: [
        { id: "boutonniere", label: "부토니에" },
        { id: "corsage", label: "코사지" },
      ],
      correctOptionId: "boutonniere",
      phase: "draft",
      scoring: { correct: 15, target: "table" },
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-relationship",
      mode: "poll",
      prompt: "오늘 이 자리에 가장 많이 모인 인연은?",
      options: [
        { id: "school", label: "학교 친구" },
        { id: "work", label: "직장 동료" },
        { id: "friend", label: "오랜 친구" },
        { id: "family", label: "가족·친척" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-finale-mvp",
      mode: "poll",
      prompt: "오늘 가장 뜨거웠던 테이블은?",
      options: [
        { id: "table-a", label: "A TABLE" },
        { id: "table-b", label: "B TABLE" },
        { id: "table-c", label: "C TABLE" },
        { id: "table-d", label: "D TABLE" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
    {
      id: "interaction-after-song",
      mode: "poll",
      prompt: "다음 음악은 어떤 분위기로 갈까요?",
      options: [
        { id: "dance", label: "춤추는 노래" },
        { id: "singalong", label: "다 같이 떼창" },
        { id: "retro", label: "추억 소환" },
        { id: "chill", label: "대화하기 좋은 곡" },
      ],
      phase: "draft",
      resultsVisibility: "after-reveal",
      createdAt: SEEDED_AT,
    },
  ];

  const guests: Guest[] = [
    {
      id: "guest-minsu",
      displayName: "민수",
      side: "groom",
      relationshipCategory: "school",
      yearsKnown: 13,
      tableId: "table-a",
      relationshipDescription: "술 먹으면 전화하는 형",
      consentToDisplay: true,
      joinedAt: SEEDED_AT,
    },
    {
      id: "guest-jiyoon",
      displayName: "지윤",
      side: "bride",
      relationshipCategory: "work",
      yearsKnown: 4,
      tableId: "table-b",
      relationshipDescription: "야근과 디저트를 함께한 동료",
      consentToDisplay: true,
      joinedAt: SEEDED_AT,
    },
    {
      id: "guest-hyunjun",
      displayName: "현준",
      side: "groom",
      relationshipCategory: "friend",
      yearsKnown: 8,
      tableId: "table-c",
      consentToDisplay: false,
      joinedAt: SEEDED_AT,
    },
    {
      id: "guest-sora",
      displayName: "소라",
      side: "bride",
      relationshipCategory: "club",
      yearsKnown: 6,
      tableId: "table-d",
      relationshipDescription: "여행 계획을 늘 먼저 짜는 친구",
      consentToDisplay: true,
      joinedAt: SEEDED_AT,
    },
  ];

  return {
    schemaVersion: 1,
    version: 1,
    event: {
      id: "demo",
      slug: "demo",
      title: "PARTYMAKER",
      subtitle: "우리의 밤을 더 재미있게",
      status: "live",
      createdAt: SEEDED_AT,
      updatedAt: SEEDED_AT,
    },
    runtime: {
      activeStageId: "stage-check-in",
      activeCueId: "cue-welcome",
      paused: false,
      screenOverride: null,
      history: [
        {
          stageId: "stage-check-in",
          cueId: "cue-welcome",
          activatedAt: SEEDED_AT,
        },
      ],
    },
    stageOrder: stages.map((stage) => stage.id),
    stages: indexById(stages),
    cues: indexById(cues),
    guests: indexById(guests),
    tables: indexById(tables),
    missions: indexById(missions),
    missionProgress: {},
    interactions: indexById(interactions),
    responses: {},
    scoreEvents: {},
    connections: {},
    facts: {},
  };
}
